import { getCookieAuth } from '@/lib/server/auth';
import ClientBody from './ClientBody';
import ClientOnly from '@/app/components/ClientOnly';

export const metadata = {
  title: 'Notifier Device Setup',
  description: 'Generated by create next app',
}

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCookieAuth();

  return (
    <ClientOnly>
      <ClientBody googleClient={process.env.GOOGLE_ID ?? ''} user={user}>
        {children}
      </ClientBody>
    </ClientOnly>
  )
}
