import './globals.css';

export const metadata = {
  title: 'Notifier Device Setup',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body id="root">
        {children}
      </body>
    </html>
  )
}
